"""VoiceGuard V2 — JWT access tokens and opaque refresh tokens.

Design
******
- **Access tokens** are signed JWTs (HS256) with a minimal, non-biometric
  payload: ``sub`` (user_id), ``type`` (``access``), ``jti`` (unique ID),
  ``iss``, ``aud``, ``iat``, ``exp``.  They are short-lived (15 min) and held
  only in client memory.
- **Refresh tokens** are opaque, high-entropy random strings generated by
  ``secrets.token_urlsafe``.  Only a SHA-256 **hash** of a refresh token is
  stored in the database (``sessions.refresh_token``), so a database breach
  does not expose usable bearer credentials.  Refresh tokens support
  server-side revocation and rotation.

Why not JWT refresh tokens?
****************************
JWTs are stateless and cannot be revoked on the server before expiry without
extra infrastructure.  The architecture (§15, §17) stores refresh tokens in
the ``sessions`` table precisely so they can be invalidated on logout, on
password change, or when a session is rotated/revoked.  Opaque hashed refresh
tokens provide that revocation capability.

Security notes
**************
- The JWT signing secret (``VG_JWT_SECRET_KEY``) is **never** placed in a
  token payload and never exposed through responses.
- No username, email, biometric data, or other PII is embedded in the access
  token — only the user UUID.
- Issuer and audience are validated on decode, and the ``type`` claim is used
  to reject a refresh-type token wherever an access token is expected.
- ``hash_refresh_token`` uses SHA-256; the token itself is 256 bits of
  entropy, so the hash offers no reduction in strength.
"""

from __future__ import annotations

import hashlib
import secrets
import uuid
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta

import jwt

from voiceguard.config import settings

# Token type claims — used to prevent token-type confusion.
ACCESS_TOKEN_TYPE = "access"
REFRESH_TOKEN_TYPE = "refresh"

# Refresh token entropy (256 bits ≈ 43 characters of urlsafe base64).
_REFRESH_TOKEN_BYTES = 32


class TokenError(Exception):
    """Base class for token errors (never exposes internal details)."""


class InvalidTokenError(TokenError):
    """Raised when a token is malformed, expired, or fails validation."""


@dataclass(frozen=True)
class AccessTokenClaims:
    """Decoded and validated claims of an access token."""

    user_id: uuid.UUID
    jti: str
    exp: datetime


def _now() -> datetime:
    return datetime.now(UTC)


def create_access_token(
    user_id: uuid.UUID,
    *,
    jti: str | None = None,
    expires_delta: timedelta | None = None,
) -> str:
    """Create a signed JWT access token.

    Args:
        user_id: The authenticated user's UUID (stored as ``sub``).
        jti: Unique token ID; generated if omitted.
        expires_delta: Custom lifetime; defaults to configuration.

    Returns:
        A compact, signed JWT string (HS256).
    """
    expires_delta = expires_delta or timedelta(
        minutes=settings.JWT_ACCESS_TOKEN_EXPIRE_MINUTES
    )
    now = _now()
    payload = {
        "sub": str(user_id),
        "type": ACCESS_TOKEN_TYPE,
        "jti": jti or str(uuid.uuid4()),
        "iss": settings.JWT_ISSUER,
        "aud": settings.JWT_AUDIENCE,
        "iat": now,
        "nbf": now,
        "exp": now + expires_delta,
    }
    return jwt.encode(
        payload,
        settings.JWT_SECRET_KEY,
        algorithm=settings.JWT_ALGORITHM,
    )


def decode_access_token(token: str) -> AccessTokenClaims:
    """Validate a JWT access token and return its claims.

    Validates signature, expiration, issuer, audience, and the ``type``
    claim (rejects anything that is not an access token).

    Args:
        token: The JWT string.

    Returns:
        The validated claims.

    Raises:
        InvalidTokenError: If the token is malformed, expired with an
            invalid signature, wrong issuer/audience, or wrong type.
    """
    try:
        payload = jwt.decode(
            token,
            settings.JWT_SECRET_KEY,
            algorithms=[settings.JWT_ALGORITHM],
            audience=settings.JWT_AUDIENCE,
            issuer=settings.JWT_ISSUER,
            options={"require": ["sub", "type", "jti", "exp", "iat", "iss", "aud"]},
        )
    except jwt.PyJWTError as exc:
        raise InvalidTokenError("Access token is invalid or expired.") from exc

    if payload.get("type") != ACCESS_TOKEN_TYPE:
        raise InvalidTokenError("Token is not an access token.")

    try:
        user_id = uuid.UUID(str(payload["sub"]))
        exp = datetime.fromtimestamp(payload["exp"], tz=UTC)
    except (ValueError, KeyError) as exc:
        raise InvalidTokenError("Access token payload is malformed.") from exc

    return AccessTokenClaims(user_id=user_id, jti=str(payload["jti"]), exp=exp)


def generate_refresh_token() -> str:
    """Generate a new opaque refresh token (256 bits of entropy)."""
    return secrets.token_urlsafe(_REFRESH_TOKEN_BYTES)


def hash_refresh_token(token: str) -> str:
    """Return the SHA-256 hex digest of a refresh token.

    This digest is what is actually stored in the ``sessions`` table.
    """
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def generate_login_token() -> str:
    """Generate a one-time opaque login-state token (256 bits of entropy).

    Issued by the password step (step 1) and required by the secondary-factor
    step (TOTP) to link the two steps to the same authenticated user without
    trusting a client-supplied user UUID.
    """
    return secrets.token_urlsafe(_REFRESH_TOKEN_BYTES)


def hash_login_token(token: str) -> str:
    """Return the SHA-256 hex digest of a one-time login-state token.

    Only the hash is stored in ``pending_logins.token_hash``, so a database
    breach does not expose usable login tokens.
    """
    return hashlib.sha256(token.encode("utf-8")).hexdigest()
